! ----------------------------------------------------------------------------
! Project Euler - Problem 2
! https://projecteuler.net/problem=2
!
! Each new term in the Fibonacci sequence is generated by adding the previous
! two terms. By starting with 1 and 2, the first 10 terms will be:
!
!     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
!
! By considering the terms in the Fibonacci sequence whose values do not
! exceed four million, find the sum of the even-valued terms.
! ----------------------------------------------------------------------------

program problem2
  implicit none

  integer, parameter :: limit = 4000000

  integer :: sum  ! the sum of all even-valued terms < 4 mio
  integer :: prev ! the previous term in the sequence
  integer :: curr ! the current term in the sequence
  integer :: next ! the next term in the sequence

  sum  = 0
  prev = 1
  curr = 2

  do while (curr < limit)
    if (modulo(curr, 2) == 0) then
      sum = sum + curr
    end if

    next = prev + curr
    prev = curr
    curr = next
  end do

  write (*,*) sum

end program problem2
